### PR TITLE
WIP: Add initial Dockerfiles and compose file

### PR DESCRIPTION
**Pull request by tatupesonen**

### CODE REVIEW

**Comment by solita-alperttiti** [comment]
Firstly, I apologize that our answer have been lasted so long. It's great that you are interested about Koronavilkku. Are you still working with this pull request?

Anyway, I think the idea of adding some docker-compose and docker files into the project is great. However, if we'll do add it, it means also a little bit more maintenance and support work to keep these files up-to-date and help people in a case they have some problems with these. I think that is something we'll manage with, if we'll get your and the community's help.

First thing to do in any case would be to create an enhancement issue and refer to it in this pull request. After that we could continue to discuss on the issue ticket about details what our target in this would be and how we'll get there. Also, feel free to ask any help if you feel you need some.

**Comment by solita-alperttiti** [comment]
Are you still working with this pull request? If you don't, then it might be a good idea to close this one and get back to it later if needed. Is this alright for you?

**Comment by solita-alperttiti** [comment]
Closing this pr due inactivity. Feel free to re-open if needed.

**Comment by tatupesonen** [comment]
Hey! Sorry for the super late response. I haven't had that much time recently, so thank you for closing the issue.

**Pull request closed without merging**
